[package]
name = "chiefbook"
version = "0.1.0"
authors = ["mediocre <druksasha@ukr.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.13"
termion = "1.5"
rand = "0.7.3"
